### ISSUE TITLE
Windows file paths

### ISSUE THREAD

**Issue by Loupi** [sigalor/ghostscript-node#1]
Hello,

Trying the library on a windows machine. I'd like to use it on both Windows, Linux, Mac and AWS Lambda.

On Windows, looks like the backslash characters of a file should be escaped.
Here is how I'm trying to use the lib with s3 and Buffer class.

```
const downloadCommand = new GetObjectCommand({
  Bucket: bucketName,
  Key: args.key
})

const downloadResponse = await s3.send(downloadCommand)
const stream = downloadResponse.Body as Readable

const buffer = await new Promise<Buffer>((resolve, reject) => {
  const chunks: Buffer[] = []
  stream.on('data', chunk => chunks.push(chunk))
  stream.once('end', () => resolve(Buffer.concat(chunks)))
  stream.once('error', reject)
})

const renderedPages = await gs.renderPDFPagesToPNG(buffer)
```

This gives:

```
Error: Failed to determine number of pages in PDF: Command failed: gs -q -dNOPAUSE -dBATCH -dNOSAFER -dNODISPLAY -c "(C:\Users\LOUIS-~1\AppData\Local\Temp\f2a7740ebb8bc3fb5f466ab0a    GPL Ghostscript 9.55.0: Unrecoverable error, exit code 1
```

copying  the command from the error output, escaping the backslash character and running it in console works fine:
```
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dNODISPLAY -c "(C:\\Users\\LOUIS-~1\\AppData\\Local\\Temp\\fa529195fd9e4b7cde0851815e85cdbd.pdf) (r) file runpdfbegin pdfpagecount = quit"
```

Looking at the source code, it looks like only the count pages function is affected. Might be because of the -c "" argument, where content must be escaped. All other commands work without escaping.

Regards

**Comment by sigalor** [comment]
Thanks for opening this issue! If it's really only about escaping, then replacing `input` by `input.replace(/\\/g, "\\\\")` [here](https://github.com/sigalor/ghostscript-node/blob/main/index.js#L78) in `countPDFPages` should probably be enough. Then we don't even need to check if the operating system is Windows in the source, because Unix file paths don't contain backslashes anyway.

Unfortunately I don't have access to a Windows machine right now. Could you check if with this small change, the `countPDFPages` function works on Windows? If it does, please feel free to open a pull request as well!

**Comment by Loupi** [comment]
https://github.com/sigalor/ghostscript-node/pull/2

**Comment by sigalor** [comment]
Great, update published, thanks for the contribution!
